### ISSUE TITLE
Latest GrTu not compatible via CKAN - but hand-installation results in unclickable main menu links?

### ISSUE THREAD

**Issue by jonathonbarton** [linuxgurugamer/GravityTurn#10]
Probably straightforward, but GravityTurn (and only GravityTurn) makes the main menus unclickable. 

It's listed as incompatible on CKAN, and it doesn't matter whether I download the existing ZIP manually from CKAN (Gravity Turn Continued 1.8.2 updated 08/10/2021) and extract manually, or delete it and install directly from the zip on the Releases page. 

All the dependencies are present and accounted for, including the latest ClickThroughBlocker 0.1.10.17, (I thought it was the original culprit since it was MIA at first). But it's there now and the same behavior persists. Add Gravity Turn to the Game Data folder and Play (and all the other items on the page, including Quit) become unclickable. They still CLICK (react to mouse clicks) but nothing happens.
![1](https://user-images.githubusercontent.com/3887073/129092886-b1746d3b-6203-47f4-894c-fdfbc63ba74d.png)

I get the same symptoms if I add Toolbar (000_Toolbar) or Toolbar Controller (000_Toolbar Controller), and now ClickThroughBlocker to the mix as well. 

Take the 4 of them out, and it works normally.
Such a weird thing, and sort of Google Proof - the one thread I found that mentioned it was solved by installing the content via CKAN, which can't be done just yet, it seems.

**Comment by linuxgurugamer** [comment]
Would be better to post things like this on the forums, and not here.  This is a simple support request, not a bug.

This is a result of some bad updates.  To fix, do the following:

Remove the complete directories, by hand, of the Toolbar, ToolbarController, and ClickThroughBlocker, as well as GT.
Then use CKAN to reinstall them.  FYI, latest version of mod IS available via CKAN, you probably need to do a refresh

**Comment by jonathonbarton** [comment]
Sorry, I'd presumed a bug had crept in since you'd pushed an update 8 minutes before I downloaded the release from yesterday. 

> Remove the complete directories, by hand, of the Toolbar, ToolbarController, and ClickThroughBlocker, as well as GT.

I know you have no way of knowing this since this is the first bug report you've gotten from me, ever, but I'm not a novice to KSP or software development in general - those are the very most basic troubleshooting steps I'd taken (repeatedly) to isolate the behavior and come to definitive Steps to Reproduce before opening a bug on it.

> Then use CKAN to reinstall them.

That's the obvious solution, but it isn't possible. I'd also presumed that it might take a while for the updates to get picked up by CKAN, which is why I waited before presuming possible bug vs. probable user error. When I could not get correct behavior by force-downloading the modules from CKAN *OR* downloading them from the Github Releases, again, I presumed bug over user error, since I've been installing and troubleshooting KSP mods for more than 5 years at this point. /shrug

![0](https://user-images.githubusercontent.com/3887073/129109668-b7d71159-e7bc-4096-b3f0-c7a82e7408f6.png)

FWIW, CKAN is set to check for CKAN client updates on launch and also to refresh repositories on launch. 

ClickThroughBlocker is MIA from is:compatible.
GravityTurn (by any name) is definitely not present in is:compatible. 
Toolbar and Toolbar Controller are also not present in is:compatible.

![4](https://user-images.githubusercontent.com/3887073/129109275-97b64434-67d1-463f-978c-156c90e35b53.png)
![1](https://user-images.githubusercontent.com/3887073/129109258-b374ef98-fd2c-4200-ab38-b6bc13f279ad.png)
![2](https://user-images.githubusercontent.com/3887073/129109267-2b5adc7a-709f-4e0d-9e09-79cf265f7eed.png)

If you remove the is:compatible filter, they're in the list, but not installable. 

![5](https://user-images.githubusercontent.com/3887073/129109287-12573872-518c-4911-85a4-74c112e57808.png)

That may be a different issue between the Releases and CKAN.

**Comment by linuxgurugamer** [comment]
Again, post on the forums, not here.  It's working for other people and myself.
Among other things, since you've never posted before, you don't' seen to know the obvious step of providing a log file for diagnosis.  So I have no way ofeven knowing what's actually installed.  
You didn't even say which version of KSP you are running.
What versions of KSP do you have set as compatible?  In CKAN, make sure you have 1.8 through 1.12 all set as compatible, I haven't finished updating all mods to 1.12, even they are working.

Note that if you don't have ALL mods updated, it's possible that there is an incompatibility, especially with these mods youare using.

Please follow up on the forum here:  https://forum.kerbalspaceprogram.com/index.php?/topic/192590-112x-gravityturn-continued-automated-efficient-launches/

You will be able to be helped by other people, and see what issues they had as well as how they were fixed.
