### ISSUE TITLE
Mod Not working

### ISSUE THREAD

**Issue by MrSteve135** [linuxgurugamer/GravityTurn#18]
I added the Mod to my GameData folder, and it doesn't show up in Game

**Comment by linuxgurugamer** [comment]
This mod has dependencies, if those aren't installed it won't work:

[Click Through Blocker](https://forum.kerbalspaceprogram.com/index.php?/topic/170747-141-click-through-blocker/)
[ToolbarController](https://forum.kerbalspaceprogram.com/index.php?/topic/169509-141-toolbar-controller-for-modders/)

Best way to install any of my mods is using CKAN, which will install all needed dependencies

**Comment by MrSteve135** [comment]
Thank you
