### ISSUE TITLE
Having Quotation Marks " " in your craft title breaks the mod.

### ISSUE THREAD

**Issue by Aceman67** [linuxgurugamer/GravityTurn#6]
having Quotation Marks " " in your craft title throws up the following error (I've also included my Player.log).

GravityTurn : Exception: System.ArgumentException: Illegal characters in path.
  at System.IO.Path.GetFileName (System.String path) [0x0001b] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at KSP.IO.IOUtils.GetFilePathFor (System.Type T, System.String file, Vessel flight) [0x00066] in <c1858a3f77504bd1aaa946fdccf84670>:0 
  at GravityTurn.LaunchDB.GetBaseFilePath (System.Type t, System.String sub) [0x00000] in <0823771a34ff4dd5a287402712751abe>:0 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

File 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program/GameData/GravityTurn/PluginData/gt_launchdb_KAN-02 "Progress II"_Kerbin.cfg' does not exist
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

File 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GravityTurn\Plugins/PluginData/GravityTurn\gt_window_6378071.cfg' does not exist
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

File 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GravityTurn\Plugins/PluginData/GravityTurn\gt_window_6378072.cfg' does not exist
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

File 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GravityTurn\Plugins/PluginData/GravityTurn\gt_window_548302.cfg' does not exist
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

File 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GravityTurn\Plugins/PluginData/GravityTurn\gt_window_6378074.cfg' does not exist

This makes the mod unresponsive as soon as you leave atmo, abort button becomes unresponsive and time warp becomes impossible.

[Player.zip](https://github.com/linuxgurugamer/GravityTurn/files/5604623/Player.zip)

**Comment by linuxgurugamer** [comment]
The obvious answer is don't use Quotes, but I'll take a look

**Comment by linuxgurugamer** [comment]
Fixed
